name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: "aykut___1995@hotmail.com"
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"backend_web","appname":"love_pet_api","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
