name: Package api

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    uses: aykut-bozkurt/love-pet/.github/workflows/test.yml

  package:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aykut-bozkurt'
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
      - name: Publish package
        working-directory: ./backend
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
