name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Go to service directory
        run: cd backend

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
          HTTP_SERVER_PORT: 3001
          TOKEN_KEY: 481URqU1bvDaoH+kw0AcMoaR2sL/tsnBQ/9w+Rl3z8U=
          DB_HOST: postgres
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres